name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Make
        run: sudo apt-get install make

      - name: Run make all
        run: make all

      - name: Run make test-all
        run: make test-all
